name: kwik_kenya
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+2

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  flutter_bloc: ^9.0.0
  go_router: ^14.8.0
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  change_app_package_name: ^1.4.0
  custom_progressbar: ^0.0.2
  google_fonts: ^6.2.1
  get_it: ^8.0.2
  easy_date_timeline: ^2.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.3.1
  intl: ^0.19.0
  webview_flutter: ^4.10.0
  pull_down_button: ^0.10.2
  flutter_svg: ^2.0.14
  provider: ^6.0.0
  flagsmith: ^6.0.0
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.1
  get_ip_address: ^0.0.7
  http: ^1.2.2
  webview_flutter_wkwebview: ^3.16.2
  shared_preferences: ^2.5.1
  in_app_review: ^2.0.9
  flutter_email_sender: ^6.0.3
  gaimon: ^1.3.2
  flutter_app_info: 
  is_first_run: ^1.0.0
  connectivity_plus: ^6.1.0
  smooth_page_indicator: ^1.2.0+3
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.6
  share_plus: ^10.1.4
  percent_indicator: ^4.2.2
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/

flutter_launcher_icons:
      android: "launcher_icon"
      ios: true
      remove_alpha_ios: true
      image_path: "assets/images/icon.png"
      min_sdk_android: 24 # android min sdk min:16, default 21
      adaptive_icon_background: "#4A4A4C" # You can use a color or image for the background
      adaptive_icon_foreground: "assets/images/icon.png" # For adaptive icons on Android

flutter_native_splash:
  color: "#010101"
  image: assets/images/icon.png
  android_12: 
    image: assets/images/icon.png
    color: "#010101"
